"""Render the profile: the SKILL.md projection and the web review page.

The skill-file projection is the Phase 2 exit criterion made concrete: the
document every Claude session reads for calibration is generated from the
evidence fold, never edited by hand. Structural boilerplate (headings,
framing paragraphs) lives here; every substantive sentence is a claim.
"""

from __future__ import annotations

import datetime
import html

from . import theme
from .inlinemd import inline_html
from .profile import ProfileState

# (field, lead-in line or None, render style)
_WHO_SECTIONS = (
    ("background", None, "para"),
    ("education", None, "para"),
    ("tracks", None, "para"),
    ("style", "**Learning style:**", "bullets"),
    ("domain_bias", None, "para"),
    ("pacing", None, "para"),
)
_CALIBRATE_SECTIONS = (
    ("calibration", None, "para"),
    ("skip", "**What to skip:**", "bullets"),
    ("scaffold", "**What to scaffold:**", "bullets"),
)


def _emit(state: ProfileState, sections) -> list[str]:
    out: list[str] = []
    for field, lead, style in sections:
        claims = state.field_claims(field)
        if not claims:
            continue
        if style == "bullets":
            block = ([lead] if lead else []) + [f"- {c.text}" for c in claims]
            out.append("\n".join(block))
        else:
            out.extend(c.text for c in claims)
    return out


def render_skill_md(state: ProfileState) -> str:
    description = state.claim("meta", "description")
    desc_text = description.text if description else "Personal learning profile."
    today = datetime.date.today().isoformat()

    parts: list[str] = []
    parts.append("---")
    parts.append("name: learner-profile")
    parts.append(f"description: {desc_text}")
    parts.append("---")
    parts.append("")
    parts.append("# Learner Profile")
    parts.append("")
    parts.append(
        "This skill provides Claude with context about who the learner is, so "
        "that explanations, exercises, and curriculum materials are calibrated "
        "correctly across any project or subject.")
    parts.append("")
    parts.append(
        "Read this skill before responding to any learning-oriented request. "
        "Use it to set your baseline assumptions about what to explain, what "
        "to skip, and how to frame new ideas.")
    parts.append("")
    parts.append("## Who the Learner Is")
    parts.append("")
    parts.append("\n\n".join(_emit(state, _WHO_SECTIONS)))
    parts.append("")
    parts.append("## How to Calibrate Responses")
    parts.append("")
    parts.append("\n\n".join(_emit(state, _CALIBRATE_SECTIONS)))
    parts.append("")
    parts.append("## Adapting to Different Subjects")
    parts.append("")
    parts.append("\n\n".join(_emit(state, (("subject_adapters", None, "para"),))))

    demonstrated = state.field_claims("demonstrated")
    if demonstrated:
        parts.append("")
        parts.append("## Demonstrated in Course Work")
        parts.append("")
        parts.append(
            "Evidence accumulated from actual course activity — checkpoints "
            "and reviewed work, learner-ratified. Recent entries first tell "
            "you what has been *proven*, not merely claimed.")
        parts.append("")
        parts.append("\n".join(f"- {c.text}" for c in reversed(demonstrated)))

    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append(
        f"*Generated by curricle from the profile evidence ledger — {today}. "
        "Do not edit by hand: propose or assert evidence instead "
        "(`python -m curricle profile --help`), then re-render.*")
    parts.append("")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# The web review page
# ---------------------------------------------------------------------------

_FIELD_TITLES = {
    "meta": "Skill description", "background": "Professional background",
    "education": "Formal education", "tracks": "Prior tracks",
    "style": "Learning style", "domain_bias": "Domain preferences",
    "pacing": "Pacing", "calibration": "Calibrating responses",
    "skip": "What to skip", "scaffold": "What to scaffold",
    "subject_adapters": "Adapting to subjects",
    "demonstrated": "Demonstrated in course work",
}

_STYLE = theme.style("""\
  .wrap { max-width:840px; margin:0 auto; padding:0 24px 90px; }
  .masthead { padding:40px 0 10px; }
  h1 { font-weight:700; font-size:clamp(28px,5vw,38px); letter-spacing:-.01em;
       margin:14px 0 0; }
  .lede { margin:12px 0 0; color:var(--muted); font-size:16px; max-width:60ch; }
  h2 { font-size:20px; font-weight:700; margin:44px 0 4px; }
  .claim { border-bottom:1px solid var(--line-soft); padding:14px 0; font-size:14.5px;
           line-height:1.6; }
  .claim:last-of-type { border-bottom:none; }
  .tier { display:inline-block; font-size:11px; font-weight:700; letter-spacing:.03em;
          border-radius:999px; padding:2px 9px; background:var(--chip);
          color:var(--muted); margin-left:8px; vertical-align:1px; white-space:nowrap; }
  .tier.demonstrated { background:var(--good-soft); color:var(--good-text); }
  .tier.thin { background:var(--warn-soft); color:var(--warn-text); }
  .src { font-size:12px; font-weight:500; color:var(--muted); margin-top:5px; }
  .pendingbox { background:var(--panel); border:1.5px solid var(--accent);
                border-radius:18px; box-shadow:var(--shadow); padding:18px 22px;
                margin:26px 0; }
  .pendingbox h2 { margin:0 0 4px; font-size:18px; }
  .pendingbox .note { font-size:13.5px; color:var(--muted); margin:0 0 8px; }
  .proposal { display:flex; gap:14px; align-items:baseline; flex-wrap:wrap;
              border-bottom:1px solid var(--line-soft); padding:12px 0; font-size:14.5px; }
  .proposal:last-child { border-bottom:none; }
  .proposal .text { flex:1 1 24rem; line-height:1.6; }
  button { display:inline-flex; align-items:center; min-height:36px;
           font-size:13.5px; font-weight:600; background:var(--panel);
           border:1.5px solid var(--line); border-radius:999px; padding:5px 16px;
           color:var(--muted); cursor:pointer;
           transition:border-color .2s, color .2s, background .2s; }
  button.yes { color:var(--good-text); border-color:var(--good); }
  button.yes:hover { background:var(--good-soft); }
  button.no { color:var(--warn-text); }
  button.no:hover { background:var(--warn-soft); border-color:var(--warn-text); }
""")


def render_profile_page(state: ProfileState, tenant_slug: str) -> str:
    e = html.escape
    parts: list[str] = []

    if state.pending:
        rows = []
        for p in state.pending:
            note = " <span class=\"tier thin\">supersedes</span>" if p.supersedes else ""
            src = f'<div class="src">{e(p.source)}</div>' if p.source else ""
            rows.append(
                f'<div class="proposal"><span class="text">'
                f'{inline_html(p.text)}'
                f'<span class="tier {e(p.tier)}">{e(p.tier)}</span>{note}{src}</span>'
                f'<button class="yes" onclick="act(\'accept\',\'{e(p.field)}\',\'{e(p.key)}\')">Accept</button>'
                f'<button class="no" onclick="act(\'reject\',\'{e(p.field)}\',\'{e(p.key)}\')">Reject</button>'
                "</div>")
        parts.append('<div class="pendingbox"><h2>Awaiting your review</h2>'
                     '<p class="note">'
                     "The system proposes; you publish. Nothing below renders into "
                     "the profile until accepted.</p>"
                     + "".join(rows) + "</div>")

    for field in _FIELD_TITLES:
        claims = state.field_claims(field)
        if not claims:
            continue
        items = []
        for c in claims:
            src = f'<div class="src">{e(c.source)}</div>' if c.source else ""
            items.append(f'<div class="claim">{inline_html(c.text)}'
                         f'<span class="tier {e(c.tier)}">{e(c.tier)}</span>{src}</div>')
        parts.append(f"<h2>{e(_FIELD_TITLES[field])}</h2>" + "".join(items))

    body = "\n".join(parts) or (
        '<p class="lede">Nothing on the record yet. Assert something in your '
        "own voice (<code>python -m curricle profile assert</code>) or let course "
        "activity propose evidence as you work.</p>")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>curricle — profile</title>
<style>
{_STYLE}</style>
</head>
<body>
<div class="wrap">
  <header class="masthead">
    <p class="eyebrow"><a href="/">← your courses</a>
    <span class="sep">·</span> the learner profile
    <span class="sep">·</span> tenant {e(tenant_slug)}</p>
    <h1>What the record says about you</h1>
    <p class="lede">Every course is calibrated from this ledger — the better it
    knows you, the less time you spend on things you already know.</p>
  </header>
  {body}
  <footer>
    Every entry is evidence with a provenance tier: <b>attested</b> — you said it;
    <b>demonstrated</b> — course activity proved it; <b>thin</b> — claimed but
    uncorroborated. The skill file Claude reads is a projection of this ledger
    (<code>python -m curricle profile render</code>).
  </footer>
</div>
<script>
function act(kind, field, key) {{
  fetch("/api/profile/events", {{ method: "POST",
    headers: {{ "Content-Type": "application/json" }},
    body: JSON.stringify({{ kind, field, key }}) }})
    .then(() => location.reload());
}}
</script>
</body>
</html>
"""
