"""The profile pipeline: evidence ledger, review discipline, projection."""

import os
import re
import unittest

import yaml

from curricle import db, profile
from curricle.profilerender import (render_profile_page, render_skill_md,
                                    skill_parts)

from corpuspaths import HAVE_TF, TF_ROOT
from pg import test_engine

SEED = [
    {"field": "meta", "key": "description", "text": "A test learner.",
     "tier": "attested", "source": "seed"},
    {"field": "background", "key": "swe",
     "text": "**Professional background:** Test engineer.", "tier": "attested"},
    {"field": "style", "key": "code-first",
     "text": "Learns by implementing.", "tier": "attested"},
    {"field": "skip", "key": "basics",
     "text": "Don't explain loops.", "tier": "attested"},
]


class FoldTest(unittest.TestCase):
    def test_assert_propose_accept_reject_retract(self):
        st = profile.fold([
            ("assert", "style", "code-first",
             {"text": "Learns by implementing.", "tier": "attested"}),
            ("propose", "style", "code-first",
             {"text": "Prefers diagrams now.", "tier": "thin", "source": "guess"}),
            ("propose", "pacing", "hours",
             {"text": "10 hrs/week.", "tier": "thin", "source": "guess"}),
            ("reject", "pacing", "hours", {}),
            ("propose", "demonstrated", "tf--q1",
             {"text": "Quiz 9/10.", "tier": "demonstrated", "source": "tf/q1"}),
            ("accept", "demonstrated", "tf--q1", {}),
        ])
        # A pending proposal never renders; the accepted claim stands.
        self.assertEqual(st.claim("style", "code-first").text,
                         "Learns by implementing.")
        self.assertEqual([p.key for p in st.pending], ["code-first"])
        self.assertTrue(st.pending[0].supersedes)
        self.assertIsNone(st.claim("pacing", "hours"))
        self.assertEqual(st.claim("demonstrated", "tf--q1").tier, "demonstrated")

    def test_supersede_and_retract(self):
        st = profile.fold([
            ("assert", "pacing", "hours", {"text": "3-5 hrs.", "tier": "attested"}),
            ("assert", "pacing", "hours", {"text": "5-8 hrs.", "tier": "attested"}),
            ("assert", "skip", "basics", {"text": "No loops.", "tier": "attested"}),
            ("retract", "skip", "basics", {}),
        ])
        self.assertEqual(st.claim("pacing", "hours").text, "5-8 hrs.")
        self.assertIsNone(st.claim("skip", "basics"))

    def test_validation(self):
        with self.assertRaises(profile.InvalidProfileEvent):
            profile.validate_profile_event("propose", "vibe", "x", {"text": "t", "tier": "thin"})
        with self.assertRaises(profile.InvalidProfileEvent):
            profile.validate_profile_event("assert", "style", "x", {"text": "t", "tier": "high"})
        with self.assertRaises(profile.InvalidProfileEvent):
            profile.validate_profile_event("assert", "style", "x", {"tier": "attested"})


class ProjectionTest(unittest.TestCase):
    def test_skill_md_projection(self):
        st = profile.fold([
            ("assert", c["field"], c["key"],
             {"text": c["text"], "tier": c["tier"], "source": c.get("source")})
            for c in SEED
        ] + [
            ("propose", "demonstrated", "tf--q1",
             {"text": "tf — **Phase 1**: 9/10", "tier": "demonstrated",
              "source": "tf/q-phase-1"}),
            ("accept", "demonstrated", "tf--q1", {}),
        ])
        md = render_skill_md(st)
        self.assertIn("name: learner-profile", md)
        self.assertIn("description: A test learner.", md)
        self.assertIn("**Professional background:** Test engineer.", md)
        self.assertIn("- Learns by implementing.", md)
        self.assertIn("**What to skip:**\n- Don't explain loops.", md)
        self.assertIn("## Demonstrated in Course Work", md)
        self.assertIn("tf — **Phase 1**: 9/10", md)
        self.assertIn("Generated by curricle", md)

    def test_a_section_with_no_claims_prints_no_heading(self):
        # F30. A learner who skipped "Subjects" got "## Adapting to Different
        # Subjects" over nothing — which reads to a model as a section that
        # was considered and came back empty, and to the learner reviewing
        # their own document as a promise the form failed to keep.
        st = profile.fold([
            ("assert", c["field"], c["key"],
             {"text": c["text"], "tier": c["tier"], "source": c.get("source")})
            for c in SEED])
        md = render_skill_md(st)
        self.assertIn("## Who the Learner Is", md)
        self.assertNotIn("## Adapting to Different Subjects", md)
        # And the heading comes back the moment the field has a claim.
        answered = profile.fold([
            ("assert", "subject_adapters", "any",
             {"text": "Subject-agnostic.", "tier": "attested"})])
        self.assertIn("## Adapting to Different Subjects",
                      render_skill_md(answered))

    def test_every_part_is_tagged_and_the_join_is_the_document(self):
        # The onboarding read-back sets curricle's frame and the learner's
        # sentences in two different types (fork B), which it can only do if
        # the renderer says which is which. One renderer, one order: the
        # parts joined are the file, or the review screen is showing a
        # document nobody sends.
        st = profile.fold([
            ("assert", c["field"], c["key"],
             {"text": c["text"], "tier": c["tier"], "source": c.get("source")})
            for c in SEED])
        parts = skill_parts(st)
        self.assertEqual("\n".join(text for _, text in parts),
                         render_skill_md(st))
        mine = [text for source, text in parts if source == "learner"]
        self.assertIn("description: A test learner.", mine)
        self.assertIn("**Professional background:** Test engineer.", mine)
        self.assertIn("- Learns by implementing.", mine)
        # The frame is the house's, including the bold lead-in over a list
        # of the learner's bullets.
        house = [text for source, text in parts if source == "house"]
        self.assertIn("## Who the Learner Is", house)
        self.assertIn("**What to skip:**", house)
        self.assertIn("name: learner-profile", house)

    def test_a_house_fallback_description_is_not_the_learners_words(self):
        # Nobody wrote "Personal learning profile."; it is what the frame
        # says when the learner has said nothing.
        st = profile.fold([
            ("assert", "pacing", "hours", {"text": "3 hrs.", "tier": "attested"})])
        for source, text in skill_parts(st):
            if text.startswith("description: "):
                self.assertEqual(source, "house")
                self.assertEqual(text, "description: Personal learning profile.")
                break
        else:
            self.fail("the frontmatter lost its description line")

    def test_pending_proposals_never_render(self):
        st = profile.fold([
            ("assert", "meta", "description", {"text": "X.", "tier": "attested"}),
            ("propose", "background", "sneaky",
             {"text": "SECRET CLAIM", "tier": "thin", "source": "s"}),
        ])
        self.assertNotIn("SECRET CLAIM", render_skill_md(st))


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# The generated line carries the day the committed copy was rendered, which
# is a fact about that morning rather than about the renderer.
_RENDERED_ON = re.compile(r"ledger — \d{4}-\d{2}-\d{2}\.")


class ShippedProjectionTest(unittest.TestCase):
    """The committed pair, held to each other.

    `build/example-profile-SKILL.md` is exactly what `import-seed` plus
    `render` produce from `examples/example-profile-seed.yaml` (CLAUDE.md
    says so, and the two are regenerated together). That makes it the one
    place where a change to the projection's *bytes* is visible without a
    database — and this batch changed how the projection is assembled, to
    give the onboarding read-back a boundary between curricle's frame and
    the learner's sentences. The file a model reads had to come out
    unchanged, so it is asserted rather than eyeballed.
    """

    def test_the_example_seed_still_renders_the_committed_document(self):
        with open(os.path.join(REPO_ROOT, "examples",
                               "example-profile-seed.yaml"),
                  encoding="utf-8") as f:
            seed = yaml.safe_load(f)
        state = profile.fold([
            ("assert", c["field"], c["key"],
             {"text": c["text"], "tier": c.get("tier", "attested"),
              "source": c.get("source")})
            for c in seed["claims"]])
        with open(os.path.join(REPO_ROOT, "build",
                               "example-profile-SKILL.md"),
                  encoding="utf-8") as f:
            committed = f.read()
        self.assertEqual(_RENDERED_ON.sub("ledger — X.", render_skill_md(state)),
                         _RENDERED_ON.sub("ledger — X.", committed))


LISTY = ("This profile is subject-agnostic; the same principles apply:\n\n"
         "- Lead with **implementation** and concrete examples\n"
         "- Bridge from `engineering` intuition to formal concepts\n"
         "- Don't assume mathematical background")


class ReviewPageTest(unittest.TestCase):
    """The web projection of the same ledger.

    The claims are markdown and the long ones carry blocks; the page used to
    run them through the inline renderer, which knows nothing about lines, so
    a lede and five bullets arrived as one paragraph with " - " for a bullet
    (#16). The profile's richest content was its least readable. What must
    not move while fixing that is the tier: it is provenance, it is printed
    in words, and no claim may come out of the renderer looking like a
    different tier than it went in as.
    """

    def page(self, events):
        return render_profile_page(profile.fold(events), "example")

    def test_a_claim_s_bullets_render_as_a_list(self):
        page = self.page([("assert", "subject_adapters", "agnostic",
                           {"text": LISTY, "tier": "attested"})])
        self.assertIn("<p>This profile is subject-agnostic; the same "
                      "principles apply:</p>", page)
        self.assertIn("<li>Lead with <b>implementation</b> and concrete "
                      "examples</li>", page)
        self.assertIn("<li>Bridge from <code>engineering</code> intuition to "
                      "formal concepts</li>", page)
        self.assertEqual(page.count("<li>"), 3)
        # The defect itself: the bullets glued into the running text.
        self.assertNotIn("apply: - Lead", page)
        self.assertNotIn("\n- ", page)

    def test_a_one_paragraph_claim_still_reads_as_one_line(self):
        # The common case, and the look the page already had: the tier chip
        # trails the sentence rather than dropping to a line of its own.
        page = self.page([("assert", "pacing", "hours",
                           {"text": "Works in evening blocks.",
                            "tier": "attested"})])
        self.assertIn('<p>Works in evening blocks.'
                      '<span class="tier attested">attested</span></p>', page)

    def test_every_tier_is_still_printed_in_words(self):
        page = self.page([
            ("assert", "pacing", "hours",
             {"text": "Evening blocks.", "tier": "attested"}),
            ("propose", "demonstrated", "tf--q1",
             {"text": "tf — **Phase 1**: 9/10", "tier": "demonstrated",
              "source": "tf/q-phase-1"}),
            ("accept", "demonstrated", "tf--q1", {}),
            ("propose", "style", "diagrams",
             {"text": "Prefers diagrams:\n\n- so it is claimed",
              "tier": "thin", "source": "a guess"}),
        ])
        for tier in ("attested", "demonstrated", "thin"):
            self.assertIn(f'<span class="tier {tier}">{tier}</span>', page)
        # …including on the claim whose body ends in a list, where the chip
        # rides a line of its own rather than the last bullet.
        self.assertIn('<p class="foot"><span class="tier thin">thin</span>', page)
        self.assertNotIn("so it is claimed<span", page)

    def test_a_pending_proposal_keeps_its_source_and_its_buttons(self):
        page = self.page([("propose", "style", "diagrams",
                           {"text": "Prefers diagrams.", "tier": "thin",
                            "source": "a guess"})])
        self.assertIn("Awaiting your review", page)
        self.assertIn('<div class="src">a guess</div>', page)
        self.assertIn("act('accept','style','diagrams')", page)
        self.assertIn("act('reject','style','diagrams')", page)


class LedgerTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.engine = test_engine()
        with cls.engine.begin() as conn:
            cls.a = db.create_tenant(conn, "profile-a")
            cls.b = db.create_tenant(conn, "profile-b")

    def test_roundtrip_and_isolation(self):
        with self.engine.begin() as conn:
            profile.import_seed(conn, db.for_tenant(self.a), SEED)
            state_a = profile.load_profile(conn, db.for_tenant(self.a))
            state_b = profile.load_profile(conn, db.for_tenant(self.b))
        self.assertEqual(len(state_a.field_claims("style")), 1)
        self.assertEqual(state_b.claims, {})

    def test_db_check_refuses_unknown_kind(self):
        import sqlalchemy as sa
        with self.engine.connect() as conn:
            with self.assertRaises(sa.exc.IntegrityError):
                conn.execute(sa.insert(db.profile_events).values(
                    tenant_id=self.a, kind="whisper", field="style",
                    key="x", payload={}))
            conn.rollback()


@unittest.skipUnless(HAVE_TF, "textual-flow repo not present")
class CheckpointEvidenceTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from fastapi.testclient import TestClient

        from curricle.webapp import create_app
        cls.engine = test_engine()
        with cls.engine.begin() as conn:
            db.create_tenant(conn, "profile-webapp")
        app = create_app([TF_ROOT], tenant_slug="profile-webapp",
                         database_url=str(cls.engine.url))
        cls.client = TestClient(app)

    def test_checkpoint_result_proposes_evidence(self):
        r = self.client.post("/c/textual-flow/api/events", json={
            "kind": "checkpoint_result", "subject_id": "q-phase-1",
            "payload": {"score": 8, "total": 10,
                        "misses": ["pregenealogical vs genealogical"]}})
        self.assertEqual(r.status_code, 200, r.text)
        page = self.client.get("/profile").text
        self.assertIn("Awaiting your review", page)
        self.assertIn("8/10", page)
        self.assertIn("pregenealogical vs genealogical", page)
        # Ratify: the proposal becomes an accepted claim and leaves the queue.
        r = self.client.post("/api/profile/events", json={
            "kind": "accept", "field": "demonstrated",
            "key": "textual-flow--q-phase-1"})
        self.assertEqual(r.status_code, 200, r.text)
        self.assertEqual(r.json()["pending"], 0)
        page = self.client.get("/profile").text
        self.assertNotIn("Awaiting your review", page)
        self.assertIn("Demonstrated in course work", page)

    def test_wire_proposals_must_name_a_source(self):
        r = self.client.post("/api/profile/events", json={
            "kind": "propose", "field": "style", "key": "sneaky",
            "payload": {"text": "x", "tier": "thin"}})
        self.assertEqual(r.status_code, 422)


if __name__ == "__main__":
    unittest.main()
