"""The profile pipeline: evidence ledger, review discipline, projection."""

import os
import unittest

from curricle import db, profile
from curricle.profilerender import render_skill_md

from pg import test_engine

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TF_ROOT = os.path.join(os.path.dirname(HERE), "textual-flow")

SEED = [
    {"field": "meta", "key": "description", "text": "A test learner.",
     "tier": "attested", "source": "seed"},
    {"field": "background", "key": "swe",
     "text": "**Professional background:** Test engineer.", "tier": "attested"},
    {"field": "style", "key": "code-first",
     "text": "Learns by implementing.", "tier": "attested"},
    {"field": "skip", "key": "basics",
     "text": "Don't explain loops.", "tier": "attested"},
]


class FoldTest(unittest.TestCase):
    def test_assert_propose_accept_reject_retract(self):
        st = profile.fold([
            ("assert", "style", "code-first",
             {"text": "Learns by implementing.", "tier": "attested"}),
            ("propose", "style", "code-first",
             {"text": "Prefers diagrams now.", "tier": "thin", "source": "guess"}),
            ("propose", "pacing", "hours",
             {"text": "10 hrs/week.", "tier": "thin", "source": "guess"}),
            ("reject", "pacing", "hours", {}),
            ("propose", "demonstrated", "tf--q1",
             {"text": "Quiz 9/10.", "tier": "demonstrated", "source": "tf/q1"}),
            ("accept", "demonstrated", "tf--q1", {}),
        ])
        # A pending proposal never renders; the accepted claim stands.
        self.assertEqual(st.claim("style", "code-first").text,
                         "Learns by implementing.")
        self.assertEqual([p.key for p in st.pending], ["code-first"])
        self.assertTrue(st.pending[0].supersedes)
        self.assertIsNone(st.claim("pacing", "hours"))
        self.assertEqual(st.claim("demonstrated", "tf--q1").tier, "demonstrated")

    def test_supersede_and_retract(self):
        st = profile.fold([
            ("assert", "pacing", "hours", {"text": "3-5 hrs.", "tier": "attested"}),
            ("assert", "pacing", "hours", {"text": "5-8 hrs.", "tier": "attested"}),
            ("assert", "skip", "basics", {"text": "No loops.", "tier": "attested"}),
            ("retract", "skip", "basics", {}),
        ])
        self.assertEqual(st.claim("pacing", "hours").text, "5-8 hrs.")
        self.assertIsNone(st.claim("skip", "basics"))

    def test_validation(self):
        with self.assertRaises(profile.InvalidProfileEvent):
            profile.validate_profile_event("propose", "vibe", "x", {"text": "t", "tier": "thin"})
        with self.assertRaises(profile.InvalidProfileEvent):
            profile.validate_profile_event("assert", "style", "x", {"text": "t", "tier": "high"})
        with self.assertRaises(profile.InvalidProfileEvent):
            profile.validate_profile_event("assert", "style", "x", {"tier": "attested"})


class ProjectionTest(unittest.TestCase):
    def test_skill_md_projection(self):
        st = profile.fold([
            ("assert", c["field"], c["key"],
             {"text": c["text"], "tier": c["tier"], "source": c.get("source")})
            for c in SEED
        ] + [
            ("propose", "demonstrated", "tf--q1",
             {"text": "tf — **Phase 1**: 9/10", "tier": "demonstrated",
              "source": "tf/q-phase-1"}),
            ("accept", "demonstrated", "tf--q1", {}),
        ])
        md = render_skill_md(st)
        self.assertIn("name: learner-profile", md)
        self.assertIn("description: A test learner.", md)
        self.assertIn("**Professional background:** Test engineer.", md)
        self.assertIn("- Learns by implementing.", md)
        self.assertIn("**What to skip:**\n- Don't explain loops.", md)
        self.assertIn("## Demonstrated in Course Work", md)
        self.assertIn("tf — **Phase 1**: 9/10", md)
        self.assertIn("Generated by curricle", md)

    def test_pending_proposals_never_render(self):
        st = profile.fold([
            ("assert", "meta", "description", {"text": "X.", "tier": "attested"}),
            ("propose", "background", "sneaky",
             {"text": "SECRET CLAIM", "tier": "thin", "source": "s"}),
        ])
        self.assertNotIn("SECRET CLAIM", render_skill_md(st))


class LedgerTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.engine = test_engine()
        with cls.engine.begin() as conn:
            cls.a = db.create_tenant(conn, "profile-a")
            cls.b = db.create_tenant(conn, "profile-b")

    def test_roundtrip_and_isolation(self):
        with self.engine.begin() as conn:
            profile.import_seed(conn, db.for_tenant(self.a), SEED)
            state_a = profile.load_profile(conn, db.for_tenant(self.a))
            state_b = profile.load_profile(conn, db.for_tenant(self.b))
        self.assertEqual(len(state_a.field_claims("style")), 1)
        self.assertEqual(state_b.claims, {})

    def test_db_check_refuses_unknown_kind(self):
        import sqlalchemy as sa
        with self.engine.connect() as conn:
            with self.assertRaises(sa.exc.IntegrityError):
                conn.execute(sa.insert(db.profile_events).values(
                    tenant_id=self.a, kind="whisper", field="style",
                    key="x", payload={}))
            conn.rollback()


@unittest.skipUnless(os.path.isdir(TF_ROOT), "textual-flow repo not present")
class CheckpointEvidenceTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from fastapi.testclient import TestClient

        from curricle.webapp import create_app
        cls.engine = test_engine()
        with cls.engine.begin() as conn:
            db.create_tenant(conn, "profile-webapp")
        app = create_app([TF_ROOT], tenant_slug="profile-webapp",
                         database_url=str(cls.engine.url))
        cls.client = TestClient(app)

    def test_checkpoint_result_proposes_evidence(self):
        r = self.client.post("/c/textual-flow/api/events", json={
            "kind": "checkpoint_result", "subject_id": "q-phase-1",
            "payload": {"score": 8, "total": 10,
                        "misses": ["pregenealogical vs genealogical"]}})
        self.assertEqual(r.status_code, 200, r.text)
        page = self.client.get("/profile").text
        self.assertIn("Awaiting your review", page)
        self.assertIn("8/10", page)
        self.assertIn("pregenealogical vs genealogical", page)
        # Ratify: the proposal becomes an accepted claim and leaves the queue.
        r = self.client.post("/api/profile/events", json={
            "kind": "accept", "field": "demonstrated",
            "key": "textual-flow--q-phase-1"})
        self.assertEqual(r.status_code, 200, r.text)
        self.assertEqual(r.json()["pending"], 0)
        page = self.client.get("/profile").text
        self.assertNotIn("Awaiting your review", page)
        self.assertIn("Demonstrated in course work", page)

    def test_wire_proposals_must_name_a_source(self):
        r = self.client.post("/api/profile/events", json={
            "kind": "propose", "field": "style", "key": "sneaky",
            "payload": {"text": "x", "tier": "thin"}})
        self.assertEqual(r.status_code, 422)


if __name__ == "__main__":
    unittest.main()
